# Site title (displayed in the header)
# Used for SEO by default but can be overridden in individual pages
title: MelliMoe

# Site description (displayed in the header)
# Used for SEO by default but can be overridden in individual pages
description: The Art of Moe Moen

# Site author
# Used for SEO by default but can be overridden in individual pages
author: Shelby Moen

# Path of site logo (used for SEO)
# Only change the image file itself, not the path!
logo: &logo /assets/img/seo-logo.png

# Path of site logo (displayed in the site banner/header)
# Only change the image file itself, not the path!
site-logo: /assets/img/logo.svg

# Website URL (used for SEO and sitemap.xml generation)
url: https://mellimoe.github.io

# Add an additional layer to the website URL, like this: "/some-other-name"
baseurl: ""

# Enter Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: G-L94SKQV3YR

# Specify social profiles for Google (used for SEO)
social:
  name: Shelby Moen
  links:
    - https://twitter.com/missmellifluous
    - https://www.linkedin.com/in/shelby-ann-moen
    - https://instagram.com/melli.moe

# Includes an icon in the footer for each username
footer-links:
  email: shelbyamoen@gmail.com
  instagram: melli.moe
  linkedin: shelby-ann-moen
  twitter: missmellifluous

# Ordered list of categories for portfolio posts
portfolio-categories:
  - Digital Design
  - Print Design
  - Illustration

# Manual collections ordering doesn't work until Github moves to Jekyll4.0
# For now there's some nested for loop hack in layouts
menu-order:
  - about
portfolio-order:
  - fccl
  - savings-ad
  - instagram-stories
  - social-media-ads
  - opening-day
  - sellers-guide
  - communication-flyer
  - loop-flyer
  - app-store
  - luxury-brochure
  - targeted-mailer
  - pokemon-tropical
  - futari-wa
  - casino-royale-precure
  - wooloo
  - to-the-moon
  - promise
  - oh-my-stars
  - everybodys-satellite
  - crumbling
  - just-peachy

#
# !! Don't need to change any of the configuration flags below !!
#

# General configurations
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
permalink: /:title/

# Collections for general pages and portfolio posts
collections_dir: pages
collections:
  menu:
    output: true
    permalink: /:title/
  portfolio:
    output: true
    permalink: /:collection/:title/ # Add slugified_categories for Jekyll4.1

# Front matter defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "general"
      image: *logo
  - scope:
      path: ""
      type: "portfolio"
    values:
      layout: "portfolio"

# Set the Sass partials directory
sass:
  sass_dir: _sass
  style: :compressed # Either :expanded or :compressed

# Use the following plug-ins
plugins:
  - jemoji # Emoji please!
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-seo-tag # Auto generate SEO tags

# Exclude these files from production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
