# Name of site (displayed in the header)
site-name: MelliMoe

# Short tagline (displayed in the header)
site-tagline: The art of Moe Moen

# Longer site description (used for SEO)
description: The art of Moe Moen

# Author name (used for SEO)
author: Shelby Moen

# Path of site logo
logo:

# Includes an icon in the footer for each username
footer-links:
  email: shelbyamoen@gmail.com
  instagram: melli.moe
  linkedin: shelby-ann-moen
  twitter: missmellifluous

# Specify social profiles for Google
social:
  name: Shelby Moen
  links:
    - https://twitter.com/missmellifluous
    - https://www.linkedin.com/in/shelby-ann-moen
    - https://instagram.com/melli.moe

# Ordered list of categories for portfolio posts
portfolio-categories:
  - Digital Design
  - Print Design
  - Illustration

# Manual collections ordering doesn't work until Github moves to Jekyll4
# For now there's some nested for loop hack in layouts
menu-order:
  - about
  - contact
portfolio-order:
  - social-media-ads
  - communication-flyer
  - luxury-brochure
  - targeted-mailer
  - to-the-moon
  - promise
  - oh-my-stars
  - everybodys-satellite
  - crumbling

# Enter Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Website URL
url: http://mellimoe.github.io

# Add an additional layer to the website URL, like this: "/some-other-name"
baseurl: ""

#
# !! Don't need to change any of the configuration flags below !!
#

# General configurations
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
permalink: /:title/

# Collections for general pages and portfolio posts
collections_dir: pages
collections:
  general:
    output: true
    permalink: /:title/
  portfolio:
    output: true
    permalink: /:collection/:categories/:title/

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "general"
    values:
      layout: "general"
  -
    scope:
      path: ""
      type: "portfolio"
    values:
      layout: "portfolio"

# Set the Sass partials directory
sass:
  sass_dir: _sass
  style: :compressed # Either :expanded or :compressed

# Use the following plug-ins
plugins:
  - jemoji # Emoji please!
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-seo-tag # Auto generate SEO tags

# Exclude these files from production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
